### ISSUE TITLE
Drive not considered in resulting m3u filepaths.

### ISSUE THREAD

**Issue by Tjerbor** [MartinHH/CrateToM3U#10]
My input
![2](https://user-images.githubusercontent.com/44727916/201799082-6b2754ef-05b6-4d7b-9c56-cb54adfc361a.PNG)

The result
![1](https://user-images.githubusercontent.com/44727916/201799077-1e0f1913-ad59-4dc4-9989-b2c0f0375428.PNG)

As you can see the resulting paths in the m3u file should start with M:/Musik...

There's probably a simple fix to this but i don't program in scala.

**Comment by MartinHH** [comment]
By default, audio file paths are exported in the exact same format as serato stores them in the `.crate`-files.

If you need something else, you can use the options `-a`, `-b` and `-r` to manipulate those paths. In your case that should be `-a M:/`.

Please leave a brief reply as confirmation if that solves your problem (I'm 99% sure, but do not have access to a Windows machine to test it).



P.S.: I would not want to change the default behaviour to your expectations because:

1. relative paths in the output files are useful for some use cases.
2. the correct implementation would be OS-specific (and I currently don't even have the means to test this under Windows).

**Comment by Tjerbor** [comment]
yes the -a command was the solution for 99% percent of the music. some music is also stored on other drives so i would still have to edit those myself...
Isn't there a way to get the full root path of a file?
And if you want to test something on windows you could use a Virtual Machine.

Not sure if you wanna improve this old project. Thanks anyway.

**Comment by MartinHH** [comment]
> some music is also stored on other drives so i would still have to edit those myself

If I remember correctly, Serato works like this: if you have a crate "X" containing files from multiple drives, then Serato would store `X.crate`-files on the various drives, each containing the partial content of the crate that is stored on the corresponding drive. So I doubt that you could run into a situation where a .crate-file stored on drive `X:` contains files on any other drive than `X:`.

> Not sure if you wanna improve this old project.

To be honest: seeing that it works fine for me and I have other priorities, I don't see myself working on that anytime soon.

One last thing: are you aware that there's also https://gitlab.com/eladmaz/SeratoCrateExporter ? I've never tried it, but if my little old tool here is not exactly what you're looking for, you might want to give that one a try.
