### ISSUE TITLE
How to build into a binary

### ISSUE THREAD

**Issue by idealerror** [MartinHH/CrateToM3U#2]
I'm curious - your docs mention a built binary, but doesn't seem like it.  How do you build this into a binary to run?

**Comment by MartinHH** [comment]
I'll try to give a brief rundown how I do/did this - feel free to ask whereever I do not give enough details for you to follow:

1. You need to have java installed (both for building the binary and then later to run it).
2. This project uses sbt (the scala build tool), so you need to have that installed: https://www.scala-sbt.org/1.x/docs/Setup.html
3. Once you have those installed: go into the root directory of this repository and run `sbt packageBin`. This will create a runnable jar under `./target/scala-2.13` (the 2.13 part may change in future versions as it corresponds to the scala version being used which is 2.13.4 at the time of writing this).
4. Move/copy that runnable jar (`cratetom3u_2.13-0.2.3.jar`) into a directoy of your choice.
5.  Download / copy the jars for the libraries used by this project (`scallop`, `scala-library` and `scala-reflect`) to the same directory (you should already have them somewhere within `~/.ivy2/cache/` due to the previous steps).
6. Create an executable shell script named `cratetom3u` that executes the java command to run the runnable jar. I pasted mine below (You would have to replace `/usr/local/Cellar/cratetom3u/0.2.1/libexec/*` with the path to the directory you placed the jars in.):
 
```
#!/bin/bash
exec java -cp "/usr/local/Cellar/cratetom3u/0.2.1/libexec/*" io.github.martinhh.sl.CrateToM3U "$@"
```



Note:
1. The above process could probably be improved. For example, one could create a "fat jar" that contains all dependencies so that you could omit step 5 - there's an sbt plugin that allows that (see https://www.baeldung.com/scala/sbt-fat-jar ). Futhermore, there would be sbt plugins for creating fully self-contained executable binaries (however: those binaries would be OS-specific). I just did not have the motivation to do any of that yet (I coded this tool years ago and once I had it working on my local machines I did not think about improving it much).
2. **If you just want to use this tool as it is and don't have a urgent need to build it yourself** and you are on OSX, you could just use homebrew to install it as described [here](https://github.com/MartinHH/CrateToM3U/wiki/Installation). (Homebrew will download the jar that I built doing steps 1-3 and then automatically do steps 5 & 6 by following [this ruby script](https://github.com/MartinHH/homebrew-beta/blob/master/cratetom3u.rb))

**Comment by MartinHH** [comment]
P.S.: I just remembered that the project actually uses the sbt-native-packager plugin which should be capable of building self-contained binaries (see https://www.scala-sbt.org/sbt-native-packager/index.html ), however as I wrote: it's been ages since I last fiddled around with this project so I would have to re-investigate how far that plugin might lead to a more convient process than the one I described above.

**Comment by MartinHH** [comment]
>     2. If you just want to use this tool as it is and don't have a urgent need to build it yourself and you are on OSX, you could just use homebrew to install it as described [here](https://github.com/MartinHH/CrateToM3U/wiki/Installation). 

I noticed that this did not work anymore due to changes in how homebrew resolves java as dependency. That is now fixed (change of line 8 [here](https://github.com/MartinHH/homebrew-beta/commit/1b84db4f57318a0c942751782bd00eab8f2cb04b)).

**Comment by idealerror** [comment]
Thanks for this!
